Clinic System/Models/ClinicType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicType()
        {
            this.HealthClinics = new HashSet<HealthClinic>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthClinic> HealthClinics { get; set; }
    }
}

Clinic System/Controllers/ClinicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinic_System.Models;

namespace Clinic_System.Controllers
{
    public class ClinicController : Controller
    {
        private ClinicSysDbEntities db = new ClinicSysDbEntities();

        // GET: Clinic
        public ActionResult Index()
        {
            var healthClinics = db.HealthClinics.Include(h => h.Campu).Include(h => h.ClinicType);
            return View(healthClinics.ToList());
        }

        // GET: Clinic/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HealthClinic healthClinic = db.HealthClinics.Find(id);
            if (healthClinic == null)
            {
                return HttpNotFound();
            }
            return View(healthClinic);
        }

        // GET: Clinic/Create

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CampusId = new SelectList(db.Campus, "Id", "Name");
            ViewBag.ClinicTypeId = new SelectList(db.ClinicTypes, "Id", "TypeName");
            return View();
        }

        // POST: Clinic/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Physical_Address,ResAddress,Phone,Email,CampusId,ClinicTypeId")] HealthClinic healthClinic)
        {
            if (ModelState.IsValid)
            {
                db.HealthClinics.Add(healthClinic);
                db.SaveChanges();
                TempData["successMessage"] = $"Item successfully added";
                return RedirectToAction("Index");
            }

            ViewBag.CampusId = new SelectList(db.Campus, "Id", "Name", healthClinic.CampusId);
            ViewBag.ClinicTypeId = new SelectList(db.ClinicTypes, "Id", "TypeName", healthClinic.ClinicTypeId);
            return View(healthClinic);
        }

        // GET: Clinic/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HealthClinic healthClinic = db.HealthClinics.Find(id);
            if (healthClinic == null)
            {
                return HttpNotFound();
            }
            ViewBag.CampusId = new SelectList(db.Campus, "Id", "Name", healthClinic.CampusId);
            ViewBag.ClinicTypeId = new SelectList(db.ClinicTypes, "Id", "TypeName", healthClinic.ClinicTypeId);
            return View(healthClinic);
        }

        // POST: Clinic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Physical_Address,ResAddress,Phone,Email,CampusId,ClinicTypeId")] HealthClinic healthClinic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(healthClinic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CampusId = new SelectList(db.Campus, "Id", "Name", healthClinic.CampusId);
            ViewBag.ClinicTypeId = new SelectList(db.ClinicTypes, "Id", "TypeName", healthClinic.ClinicTypeId);
            return View(healthClinic);
        }

        // GET: Clinic/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HealthClinic healthClinic = db.HealthClinics.Find(id);
            if (healthClinic == null)
            {
                return HttpNotFound();
            }
            return View(healthClinic);
        }

        // POST: Clinic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HealthClinic healthClinic = db.HealthClinics.Find(id);
            db.HealthClinics.Remove(healthClinic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RemoveAsset(int id)
        {
            HealthClinic healthClinic = db.HealthClinics.Find(id);
            db.HealthClinics.Remove(healthClinic);
            db.SaveChanges();
            TempData["successMessage"] = $"Asset successfully deleted";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinic System/Views/Clinic/Create.cshtml
@model Clinic_System.Models.HealthClinic

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />

    <style>
        .note {
            text-align: center;
            height: 50px;
            background: -webkit-linear-gradient(left, #0072ff, #8811c5);
            color: #fff;
            font-weight: bold;
            line-height: 50px;
        }

        .form-content {
            padding: 5%;
            border: 1px solid #ced4da;
            margin-bottom: 2%;
        }

        .form-control {
            border-radius: 1.5rem;
        }

        .btnSubmit {
            border: none;
            border-radius: 1.5rem;
            padding: 1%;
            width: 20%;
            cursor: pointer;
            background: #0062cc;
            color: #fff;
        }
    </style>
</head>
@using (Html.BeginForm("Create", "Clinic", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <body>
        <div class="container register-form">
            <div class="form">
                <div class="note">
                    <p>Clinic Details</p>
                </div>

                <div class="form-content">
                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Name), @required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.DropDownList("ClinicTypeId", null, htmlAttributes: new { @class = "form-control" })
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.ResAddress, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.ResAddress), @required = "required" } })
                                @Html.ValidationMessageFor(model => model.ResAddress, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Phone), @required = "required" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>

                        </div>
                    </div>

                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Email), @required = "required" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.DropDownList("CampusId", null, htmlAttributes: new { @class = "form-control" })
                            </div>

                        </div>
                    </div>

                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Physical_Address, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Physical_Address), @required = "required" } })
                            </div>

                        </div>
                        <div class="col-md-6">
                          

                        </div>
                    </div>
                 
                    <hr />
                    <button type="submit" onclick="return validateData();" class="btnSubmit">Submit</button>

                </div>
            </div>
        </div>


    </body>

}

</html>

Clinic System/Views/Clinic/Delete.cshtml
@model Clinic_System.Models.HealthClinic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>HealthClinic</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Physical_Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Physical_Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ResAddress)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ResAddress)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Campu.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Campu.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ClinicType.TypeName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ClinicType.TypeName)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Clinic System/Views/Clinic/Details.cshtml
@model Clinic_System.Models.HealthClinic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>HealthClinic</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Physical_Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Physical_Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ResAddress)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ResAddress)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Campu.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Campu.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ClinicType.TypeName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ClinicType.TypeName)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Clinic System/Views/Clinic/Edit.cshtml
@model Clinic_System.Models.HealthClinic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HealthClinic</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Physical_Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Physical_Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Physical_Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ResAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ResAddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ResAddress, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CampusId, "CampusId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CampusId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CampusId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ClinicTypeId, "ClinicTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ClinicTypeId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ClinicTypeId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Clinic System/Views/Clinic/Index.cshtml
@model IEnumerable<Clinic_System.Models.HealthClinic>

@{
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
 
</head>
<body>
    <p style="margin-left:25px;">
        @Html.ActionLink("Add Clinic", "Create")
    </p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Clincs Added</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Physical_Address)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.ResAddress)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Phone)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            Type
                        </th>

                        <th>Action</th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Physical_Address)
                            </td>


                            <td>
                                @Html.DisplayFor(modelItem => item.ResAddress)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Phone)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClinicType.TypeName)
                            </td>

                            <td class="btn-group">
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary fa fa-pencil-square-o" })
                                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-success fa fa-info-circle" })
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger fa fa-trash-o" })
                            </td>

                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

    <script src="~/Content/AdminTemp/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/AdminTemp/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/AdminTemp/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/AdminTemp/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/AdminTemp/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/AdminTemp/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/AdminTemp/js/demo/datatables-demo.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
    <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" />

    <link href="https://code.jquery.com/jquery-3.5.1.js" />
    <link href="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" />
    <link href="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js" />


</body>
</html>