Clinic System/Models/MedicalPractitioner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalPractitioner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalPractitioner()
        {
            this.Comments = new HashSet<Comment>();
            this.PatientAppointments = new HashSet<PatientAppointment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public bool IsRegistered { get; set; }
        public int SpecialityId { get; set; }
        public int PractitionerTypeId { get; set; }
        public int EmpTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MedicalPractitioner MedicalPractitioner1 { get; set; }
        public virtual MedicalPractitioner MedicalPractitioner2 { get; set; }
        public virtual Race Race { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments { get; set; }
    }
}

Clinic System/Controllers/MedicalPractitionerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinic_System.Models;

namespace Clinic_System.Controllers
{
    public class MedicalPractitionerController : Controller
    {
        private ClinicSysDbEntities db = new ClinicSysDbEntities();

        // GET: MedicalPractitioner
        public ActionResult Index()
        {
            var medicalPractitioners = db.MedicalPractitioners.Include(m => m.Gender).Include(m => m.Race).Include(m => m.Speciality).Include(m => m.Type);
            return View(medicalPractitioners.ToList());
        }

        // GET: MedicalPractitioner/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedicalPractitioner medicalPractitioner = db.MedicalPractitioners.Find(id);
            if (medicalPractitioner == null)
            {
                return HttpNotFound();
            }
            return View(medicalPractitioner);
        }

        // GET: MedicalPractitioner/Create
        public ActionResult Create()
        {
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name");
            ViewBag.RaceId = new SelectList(db.Races, "Id", "Type");
            ViewBag.SpecialityId = new SelectList(db.Specialities, "Id", "Name");
            ViewBag.PractitionerTypeId = new SelectList(db.Types, "Id", "Name");
            return View();
        }

        // POST: MedicalPractitioner/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Cell,Email,Address,RaceId,GenderId,IsRegistered,SpecialityId,PractitionerTypeId")] MedicalPractitioner medicalPractitioner)
        {
            if (ModelState.IsValid)
            {
                db.MedicalPractitioners.Add(medicalPractitioner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", medicalPractitioner.GenderId);
            ViewBag.RaceId = new SelectList(db.Races, "Id", "Type", medicalPractitioner.RaceId);
            ViewBag.SpecialityId = new SelectList(db.Specialities, "Id", "Name", medicalPractitioner.SpecialityId);
            ViewBag.PractitionerTypeId = new SelectList(db.Types, "Id", "Name", medicalPractitioner.PractitionerTypeId);
            return View(medicalPractitioner);
        }

        // GET: MedicalPractitioner/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedicalPractitioner medicalPractitioner = db.MedicalPractitioners.Find(id);
            if (medicalPractitioner == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", medicalPractitioner.GenderId);
            ViewBag.RaceId = new SelectList(db.Races, "Id", "Type", medicalPractitioner.RaceId);
            ViewBag.SpecialityId = new SelectList(db.Specialities, "Id", "Name", medicalPractitioner.SpecialityId);
            ViewBag.PractitionerTypeId = new SelectList(db.Types, "Id", "Name", medicalPractitioner.PractitionerTypeId);
            return View(medicalPractitioner);
        }

        // POST: MedicalPractitioner/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Cell,Email,Address,RaceId,GenderId,IsRegistered,SpecialityId,PractitionerTypeId")] MedicalPractitioner medicalPractitioner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicalPractitioner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", medicalPractitioner.GenderId);
            ViewBag.RaceId = new SelectList(db.Races, "Id", "Type", medicalPractitioner.RaceId);
            ViewBag.SpecialityId = new SelectList(db.Specialities, "Id", "Name", medicalPractitioner.SpecialityId);
            ViewBag.PractitionerTypeId = new SelectList(db.Types, "Id", "Name", medicalPractitioner.PractitionerTypeId);
            return View(medicalPractitioner);
        }

        // GET: MedicalPractitioner/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedicalPractitioner medicalPractitioner = db.MedicalPractitioners.Find(id);
            if (medicalPractitioner == null)
            {
                return HttpNotFound();
            }
            return View(medicalPractitioner);
        }

        // POST: MedicalPractitioner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MedicalPractitioner medicalPractitioner = db.MedicalPractitioners.Find(id);
            db.MedicalPractitioners.Remove(medicalPractitioner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Clinic System/Views/MedicalPractitioner/Create.cshtml
@model Clinic_System.Models.MedicalPractitioner

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script>
    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />

    <style>
        .note {
            text-align: center;
            height: 50px;
            background: -webkit-linear-gradient(left, #0072ff, #8811c5);
            color: #fff;
            font-weight: bold;
            line-height: 50px;
        }

        .form-content {
            padding: 5%;
            border: 1px solid #ced4da;
            margin-bottom: 2%;
        }

        .form-control {
            border-radius: 1.5rem;
        }

        .btnSubmit {
            border: none;
            border-radius: 1.5rem;
            padding: 1%;
            width: 20%;
            cursor: pointer;
            background: #0062cc;
            color: #fff;
        }
    </style>
</head>
@using (Html.BeginForm("Create", "MedicalPractitioner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <body>
        <div class="container register-form">
            <div class="form">
                <div class="note">
                    <p>Practitioner Info</p>
                </div>

                <div class="form-content">
                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Name), @required = "required" } })

                            </div>
                            <div class="form-group">
                                @Html.EditorFor(model => model.Cell, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Cell), @required = "required" } })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Email), @required = "required" } })

                            </div>
                            <div class="form-group">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Address), @required = "required" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.DropDownList("RaceId", null, htmlAttributes: new { @class = "form-control" })

                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.DropDownList("GenderId", null, htmlAttributes: new { @class = "form-control" })

                            </div>

                        </div>
                    </div>



                    <div class="row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.DropDownList("SpecialityId", null, htmlAttributes: new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.DropDownList("PractitionerTypeId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-6">
                    
                            <div class="form-check">
                                @Html.EditorFor(model => model.IsRegistered)
                                <label class="form-check-label" for="flexCheckDefault">
                                   Is registered?
                                </label>
                            </div>
                            </div>
                   
                    <hr />
                    <button type="submit" class="btnSubmit">Submit</button>

                </div>

            </div>

        </div>

    </body>

}

</html>

Clinic System/Views/MedicalPractitioner/Delete.cshtml
@model Clinic_System.Models.MedicalPractitioner

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>MedicalPractitioner</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Cell)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Cell)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsRegistered)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsRegistered)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gender.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gender.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Race.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Race.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Speciality.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Speciality.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Type.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Type.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Clinic System/Views/MedicalPractitioner/Details.cshtml
@model Clinic_System.Models.MedicalPractitioner

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>MedicalPractitioner</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Cell)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Cell)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsRegistered)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsRegistered)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gender.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gender.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Race.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Race.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Speciality.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Speciality.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Type.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Type.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Clinic System/Views/MedicalPractitioner/Edit.cshtml
@model Clinic_System.Models.MedicalPractitioner

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>MedicalPractitioner</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Cell, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cell, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cell, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.RaceId, "RaceId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("RaceId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RaceId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.GenderId, "GenderId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GenderId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IsRegistered, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsRegistered)
                        @Html.ValidationMessageFor(model => model.IsRegistered, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SpecialityId, "SpecialityId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SpecialityId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SpecialityId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PractitionerTypeId, "PractitionerTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PractitionerTypeId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PractitionerTypeId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Clinic System/Views/MedicalPractitioner/Index.cshtml
@model IEnumerable<Clinic_System.Models.MedicalPractitioner>

@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" />
</head>
<body>
    <p style="margin-left:25px">
        @Html.ActionLink("Add Item", "Create", "MedicalPractitioner", new { @class = "btn btn-success fa fa-plus" })
    </p>


    <div class="container mb-3 mt-3">
        <table class="table table-striped table-bordered mydataTable" id="userTable" style="width:100%">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Cell)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsRegistered)

                    </th>
                    <th>
                        Speciality

                    </th>
                    <th>Action</th> 
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cell)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.IsRegistered)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Speciality.Name)
                    </td>
                    <td class="btn btn-group">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-info fa fa-info-circle" })
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-warning fa fa-info-circle" })
                        <a onclick="RemoveItem(@item.Id)" class="btn btn-danger">Delete</a>

                    </td>
                </tr>

                }
            </tbody>
        </table>

        @section scripts{
            <script>
        $(document).ready(function () {
            $('#userTable').DataTable();
        });

     var successMessage = '@TempData["successMessage"]'
     if (successMessage != '') {
      alertify.success(successMessage);
      }

        function RemoveItem(id) {

            alertify.confirm('Clinic System', 'Are you sure you want to delete this item?', function () {
                window.location.href = '@Url.Action("RemoveAsset", "Inventory")/' + id;
            },null);
        }
            </script>
        }

    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

</body>
</html>